# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-07 05:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20180307_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
